import React from 'react';
import { Alert } from '@grafana/ui';
import { ValidationError } from './types';
import { css } from '@emotion/css';

interface Props {
  preview: string;
  errors: ValidationError[];
}

// Style for the outer container wrapping the alert box
const containerStyle = css`
  margin-top: 1rem;
`;

// Style for the query preview text block
const previewStyle = css`
  font-size: 12px;
  padding: 0;
  margin: 0;
  background-color: transparent;
  border: none;
  white-space: pre-wrap;
  word-break: break-word;
`;

/**
 * Displays a query preview with optional error messages inside a styled Alert box.
 *
 * This is typically used to show the final SQL or expression string
 * generated by a SQL builder, along with validation or syntax errors.
 *
 * @param preview - the rendered SQL or query string
 * @param errors - list of error messages to display (if any)
 */
export const QueryPreviewDisplay: React.FC<Props> = ({ preview, errors }) => {
  const hasErrors = errors.length > 0;
  const title = hasErrors ? 'Query Errors & Preview' : 'Query Preview';
  const severity = hasErrors ? 'error' : 'info';

  return (
    <div className={containerStyle}>
      <Alert title={title} severity={severity}>
        <pre className={previewStyle}>{preview}</pre>
      </Alert>
    </div>
  );
};
